spring.application.name=pop_site
server.servlet.context-path=/app


spring.datasource.url=jdbc:postgresql://${DB_HOST:localhost}:5432/popsite
spring.datasource.username=popsite
spring.datasource.password=popsite

# Crea/actualiza la tabla "canciones" automáticamente (solo para desarrollo)
spring.jpa.hibernate.ddl-auto=update
